# Generated by Django 5.0.7 on 2024-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('telefono', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=100)),
                ('nombreR', models.CharField(max_length=100)),
                ('tiempoH', models.PositiveSmallIntegerField()),
                ('mensaje', models.CharField(max_length=500)),
                ('campo11', models.DateTimeField(null=True)),
                ('campo12', models.DurationField(null=True)),
                ('campo13', models.IntegerField(null=True)),
                ('campo1', models.IntegerField(null=True)),
                ('campo3', models.CharField(max_length=100, null=True)),
                ('campo4', models.CharField(max_length=100, null=True)),
                ('campo5', models.CharField(max_length=100, null=True)),
                ('campo6', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
