# Generated by Django 5.0.6 on 2024-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('telefono', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreC', models.CharField(max_length=100)),
                ('nombreR', models.CharField(max_length=100)),
                ('tiempoH', models.PositiveSmallIntegerField()),
                ('mensaje', models.CharField(max_length=500)),
                ('campo11', models.DateTimeField()),
                ('campo12', models.DurationField()),
                ('campo13', models.IntegerField()),
                ('campo1', models.IntegerField()),
                ('campo3', models.CharField(max_length=100)),
                ('campo4', models.CharField(max_length=100)),
                ('campo5', models.CharField(max_length=100)),
                ('campo6', models.CharField(max_length=100)),
            ],
        ),
    ]
