# Generated by Django 5.0.7 on 2024-07-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='campo11',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
